
"""
AI Detector
Today's challenge is inspired by the release of ChatGPT on November 30, 2022.

Given a string of one or more sentences, determine if it was likely generated by AI using the following rules:

It contains two or more dashes (-).

It contains two or more sets of parenthesis (()). Text can be within the parenthesis.

It contains three or more words with 7 or more letters.

Words are separated by a single space and only consist of letters (A-Z). Don't include punctuation or other non-letters as part of a word.

If the given sentence meets any of the rules above, return "AI", otherwise, return "Human".


"""

def detect_ai(text):
    if text.count('-') >= 2:
        return "AI"
    parenthesis = 0
    stack = 0

    for char in text:
        if char == "(":
            stack+=1
        elif char == ")" and stack > 0:
            parenthesis += 1
            stack -=1

    if parenthesis >= 2:
        return "AI"
    text_arr = text.split(" ")
    letters = 0
    for i in text_arr:
        if len(i) >= 7:
            letters += 1
    if letters >= 3:
        return "AI"
    return "Human"

print(detect_ai("The hypersonic brown fox - jumped (over) the lazy dog."))


"""
Tests
Passed:1. detect_ai("The quick brown fox jumped over the lazy dog.") should return "Human".
Passed:2. detect_ai("The hypersonic brown fox - jumped (over) the lazy dog.") should return "Human".
Passed:3. detect_ai("Yes - you're right! I made a mistake there - let me try again.") should return "AI".
Passed:4. detect_ai("The extraordinary students were studying vivaciously.") should return "AI".
Passed:5. detect_ai("The (excited) student was (coding) in the library.") should return "AI".
"""